[2024-11-26T19:18:49.729+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-26T19:18:49.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Realtime_Data_ETL.load_weather_current_data manual__2024-11-26T19:18:46.816496+00:00 [queued]>
[2024-11-26T19:18:49.739+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Realtime_Data_ETL.load_weather_current_data manual__2024-11-26T19:18:46.816496+00:00 [queued]>
[2024-11-26T19:18:49.739+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-26T19:18:49.744+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_current_data> on 2024-11-26 19:18:46.816496+00:00
[2024-11-26T19:18:49.748+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=20117) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-26T19:18:49.749+0000] {standard_task_runner.py:63} INFO - Started process 20120 to run task
[2024-11-26T19:18:49.748+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Realtime_Data_ETL', 'load_weather_current_data', 'manual__2024-11-26T19:18:46.816496+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/ETL_weather_realtime.py', '--cfg-path', '/tmp/tmp1s_1040i']
[2024-11-26T19:18:49.750+0000] {standard_task_runner.py:91} INFO - Job 221: Subtask load_weather_current_data
[2024-11-26T19:18:49.768+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Realtime_Data_ETL.load_weather_current_data manual__2024-11-26T19:18:46.816496+00:00 [running]> on host 5de3b6ca18a7
[2024-11-26T19:18:49.834+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Shatayu' AIRFLOW_CTX_DAG_ID='Weather_Realtime_Data_ETL' AIRFLOW_CTX_TASK_ID='load_weather_current_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T19:18:46.816496+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T19:18:46.816496+00:00'
[2024-11-26T19:18:49.835+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-26T19:18:49.840+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-26T19:18:49.840+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.11-linuxkit-aarch64-with-glibc2.36
[2024-11-26T19:18:49.841+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-26T19:18:50.383+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:18:50.390+0000] {logging_mixin.py:188} INFO - Realtime Record to be pushed to snowflake table:                   date  temp  temp_feel  humidity  rain  year  month  day  hour
0 2024-11-26 14:15:00  60.1       60.1        60  2.01  2024     11   26    14
[2024-11-26T19:18:50.525+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:18:50.764+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:18:51.079+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:18:51.080+0000] {logging_mixin.py:188} INFO - Target Table Initialized and Ready to Store Realtime Weather Data from ETL
[2024-11-26T19:18:51.200+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:18:51.200+0000] {logging_mixin.py:188} INFO - An error occurred during realtime weather data load: not all arguments converted during string formatting
[2024-11-26T19:18:51.201+0000] {connection.py:762} INFO - closed
[2024-11-26T19:18:51.248+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-11-26T19:18:51.324+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-26T19:18:51.325+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-26T19:18:51.336+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Realtime_Data_ETL, task_id=load_weather_current_data, run_id=manual__2024-11-26T19:18:46.816496+00:00, execution_date=20241126T191846, start_date=20241126T191849, end_date=20241126T191851
[2024-11-26T19:18:51.360+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-26T19:18:51.375+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T19:18:51.377+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
