[2024-11-24T06:22:12.136+0000] {processor.py:161} INFO - Started process (PID=8140) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:22:12.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:22:12.140+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:22:12.138+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:22:12.146+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:22:12.144+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:22:12.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:22:12.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.032 seconds
[2024-11-24T06:22:42.403+0000] {processor.py:161} INFO - Started process (PID=8151) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:22:42.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:22:42.406+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:22:42.406+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:22:42.412+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:22:42.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:22:42.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:22:42.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.035 seconds
[2024-11-24T06:23:12.743+0000] {processor.py:161} INFO - Started process (PID=8162) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:23:12.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:23:12.747+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:23:12.747+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:23:12.753+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:23:12.752+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:23:12.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:23:12.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.047 seconds
[2024-11-24T06:23:42.953+0000] {processor.py:161} INFO - Started process (PID=8173) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:23:42.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:23:42.955+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:23:42.955+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:23:42.959+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:23:42.958+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:23:42.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:23:42.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.023 seconds
[2024-11-24T06:24:13.215+0000] {processor.py:161} INFO - Started process (PID=8184) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:24:13.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:24:13.217+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:24:13.217+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:24:13.222+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:24:13.221+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:24:13.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:24:13.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.024 seconds
[2024-11-24T06:24:43.509+0000] {processor.py:161} INFO - Started process (PID=8195) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:24:43.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:24:43.513+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:24:43.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:24:43.519+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:24:43.517+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:24:43.519+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:24:43.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.034 seconds
[2024-11-24T06:25:13.804+0000] {processor.py:161} INFO - Started process (PID=8206) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:25:13.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:25:13.808+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:25:13.808+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:25:13.812+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:25:13.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:25:13.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:25:13.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:25:44.112+0000] {processor.py:161} INFO - Started process (PID=8217) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:25:44.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:25:44.115+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:25:44.115+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:25:44.122+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:25:44.121+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:25:44.123+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:25:44.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.038 seconds
[2024-11-24T06:26:03.334+0000] {processor.py:161} INFO - Started process (PID=8228) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:26:03.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:26:03.340+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:26:03.339+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:26:03.350+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:26:03.348+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:26:03.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:26:03.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.043 seconds
[2024-11-24T06:26:33.597+0000] {processor.py:161} INFO - Started process (PID=8239) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:26:33.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:26:33.600+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:26:33.600+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:26:33.606+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:26:33.605+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:26:33.607+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:26:33.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:27:03.882+0000] {processor.py:161} INFO - Started process (PID=8250) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:03.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:27:03.885+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:27:03.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:03.890+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:27:03.889+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:27:03.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:03.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.028 seconds
[2024-11-24T06:27:13.013+0000] {processor.py:161} INFO - Started process (PID=8255) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:13.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:27:13.016+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:27:13.016+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:13.023+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:27:13.022+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:27:13.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:13.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.035 seconds
[2024-11-24T06:27:15.040+0000] {processor.py:161} INFO - Started process (PID=8260) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:15.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:27:15.042+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:27:15.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:15.048+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:27:15.047+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:27:15.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:15.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.027 seconds
[2024-11-24T06:27:19.122+0000] {processor.py:161} INFO - Started process (PID=8271) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:19.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:27:19.126+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:27:19.125+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:19.133+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:27:19.132+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:27:19.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:19.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.035 seconds
[2024-11-24T06:27:31.249+0000] {processor.py:161} INFO - Started process (PID=8276) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:31.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:27:31.251+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:27:31.251+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:31.261+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:27:31.259+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:27:31.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:27:31.277+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.034 seconds
[2024-11-24T06:28:01.553+0000] {processor.py:161} INFO - Started process (PID=8287) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:28:01.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:28:01.557+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:28:01.557+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:28:01.561+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:28:01.560+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:28:01.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:28:01.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:28:19.730+0000] {processor.py:161} INFO - Started process (PID=8298) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:28:19.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:28:19.732+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:28:19.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:28:19.736+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:28:19.735+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:28:19.736+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:28:19.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.020 seconds
[2024-11-24T06:28:50.017+0000] {processor.py:161} INFO - Started process (PID=8309) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:28:50.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:28:50.019+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:28:50.019+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:28:50.023+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:28:50.022+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:28:50.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:28:50.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.020 seconds
[2024-11-24T06:29:20.308+0000] {processor.py:161} INFO - Started process (PID=8320) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:29:20.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:29:20.311+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:29:20.310+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:29:20.315+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:29:20.314+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:29:20.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:29:20.332+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.028 seconds
[2024-11-24T06:29:44.585+0000] {processor.py:161} INFO - Started process (PID=8325) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:29:44.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:29:44.588+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:29:44.588+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:29:44.596+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:29:44.595+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:29:44.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:29:44.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.035 seconds
[2024-11-24T06:30:07.808+0000] {processor.py:161} INFO - Started process (PID=8336) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:30:07.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:30:07.809+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:30:07.809+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:30:07.814+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:30:07.813+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:30:07.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:30:07.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.020 seconds
[2024-11-24T06:30:38.102+0000] {processor.py:161} INFO - Started process (PID=8347) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:30:38.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:30:38.105+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:30:38.105+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:30:38.111+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:30:38.109+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:30:38.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:30:38.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.035 seconds
[2024-11-24T06:31:08.347+0000] {processor.py:161} INFO - Started process (PID=8358) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:31:08.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:31:08.350+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:31:08.349+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:31:08.353+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:31:08.352+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:31:08.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:31:08.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.027 seconds
[2024-11-24T06:31:22.491+0000] {processor.py:161} INFO - Started process (PID=8369) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:31:22.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:31:22.493+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:31:22.493+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:31:22.498+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:31:22.497+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:31:22.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:31:22.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.024 seconds
[2024-11-24T06:31:52.788+0000] {processor.py:161} INFO - Started process (PID=8380) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:31:52.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:31:52.790+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:31:52.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:31:52.794+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:31:52.793+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:31:52.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:31:52.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.023 seconds
[2024-11-24T06:32:23.116+0000] {processor.py:161} INFO - Started process (PID=8391) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:32:23.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:32:23.119+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:32:23.119+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:32:23.123+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:32:23.122+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:32:23.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:32:23.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:32:53.392+0000] {processor.py:161} INFO - Started process (PID=8402) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:32:53.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:32:53.394+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:32:53.394+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:32:53.398+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:32:53.397+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:32:53.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:32:53.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:32:55.416+0000] {processor.py:161} INFO - Started process (PID=8407) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:32:55.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:32:55.419+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:32:55.419+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:32:55.425+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:32:55.423+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:32:55.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:32:55.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:33:10.581+0000] {processor.py:161} INFO - Started process (PID=8412) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:33:10.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:33:10.584+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:33:10.584+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:33:10.593+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:33:10.592+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:33:10.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:33:10.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.046 seconds
[2024-11-24T06:33:40.829+0000] {processor.py:161} INFO - Started process (PID=8423) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:33:40.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:33:40.832+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:33:40.832+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:33:40.837+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:33:40.836+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:33:40.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:33:40.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:34:11.063+0000] {processor.py:161} INFO - Started process (PID=8434) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:34:11.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:34:11.066+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:34:11.065+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:34:11.071+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:34:11.070+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:34:11.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:34:11.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.026 seconds
[2024-11-24T06:34:41.308+0000] {processor.py:161} INFO - Started process (PID=8445) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:34:41.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:34:41.312+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:34:41.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:34:41.318+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:34:41.317+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:34:41.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:34:41.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.033 seconds
[2024-11-24T06:35:11.553+0000] {processor.py:161} INFO - Started process (PID=8456) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:35:11.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:35:11.554+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:35:11.554+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:35:11.558+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:35:11.557+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:35:11.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:35:11.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.020 seconds
[2024-11-24T06:35:41.811+0000] {processor.py:161} INFO - Started process (PID=8467) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:35:41.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:35:41.814+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:35:41.814+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:35:41.819+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:35:41.817+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:35:41.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:35:41.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:36:12.108+0000] {processor.py:161} INFO - Started process (PID=8478) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:36:12.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:36:12.111+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:36:12.110+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:36:12.115+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:36:12.114+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:36:12.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:36:12.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:36:42.412+0000] {processor.py:161} INFO - Started process (PID=8489) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:36:42.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:36:42.414+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:36:42.414+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:36:42.418+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:36:42.417+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:36:42.419+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:36:42.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:36:45.492+0000] {processor.py:161} INFO - Started process (PID=8494) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:36:45.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:36:45.493+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:36:45.493+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:36:45.497+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:36:45.497+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 9, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:36:45.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:36:45.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.018 seconds
[2024-11-24T06:37:05.686+0000] {processor.py:161} INFO - Started process (PID=8505) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:37:05.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:37:05.687+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:37:05.687+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:37:05.692+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:37:05.692+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:37:05.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:37:05.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.020 seconds
[2024-11-24T06:37:09.753+0000] {processor.py:161} INFO - Started process (PID=8510) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:37:09.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:37:09.756+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:37:09.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:37:09.762+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:37:09.761+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:37:09.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:37:09.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:37:30.969+0000] {processor.py:161} INFO - Started process (PID=8521) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:37:30.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:37:30.972+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:37:30.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:37:30.979+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:37:30.978+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:37:30.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:37:30.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:38:01.301+0000] {processor.py:161} INFO - Started process (PID=8532) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:38:01.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:38:01.304+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:38:01.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:38:01.309+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:38:01.307+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:38:01.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:38:01.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:38:25.571+0000] {processor.py:161} INFO - Started process (PID=8542) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:38:25.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:38:25.574+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:38:25.574+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:38:25.582+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:38:25.581+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:38:25.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:38:25.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.036 seconds
[2024-11-24T06:38:37.701+0000] {processor.py:161} INFO - Started process (PID=8547) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:38:37.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:38:37.704+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:38:37.703+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:38:37.711+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:38:37.709+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:38:37.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:38:37.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.033 seconds
[2024-11-24T06:39:08.011+0000] {processor.py:161} INFO - Started process (PID=8558) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:39:08.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:39:08.013+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:39:08.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:39:08.018+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:39:08.017+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:39:08.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:39:08.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.025 seconds
[2024-11-24T06:39:38.306+0000] {processor.py:161} INFO - Started process (PID=8569) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:39:38.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:39:38.310+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:39:38.309+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:39:38.316+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:39:38.315+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:39:38.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:39:38.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.037 seconds
[2024-11-24T06:40:08.579+0000] {processor.py:161} INFO - Started process (PID=8580) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:40:08.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:40:08.582+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:40:08.582+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:40:08.585+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:40:08.584+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:40:08.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:40:08.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.023 seconds
[2024-11-24T06:40:38.863+0000] {processor.py:161} INFO - Started process (PID=8591) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:40:38.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:40:38.867+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:40:38.867+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:40:38.873+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:40:38.871+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:40:38.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:40:38.891+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.035 seconds
[2024-11-24T06:41:09.133+0000] {processor.py:161} INFO - Started process (PID=8602) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:41:09.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:41:09.136+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:41:09.135+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:41:09.140+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:41:09.139+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:41:09.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:41:09.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.034 seconds
[2024-11-24T06:41:39.368+0000] {processor.py:161} INFO - Started process (PID=8613) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:41:39.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:41:39.371+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:41:39.371+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:41:39.375+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:41:39.374+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:41:39.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:41:39.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.029 seconds
[2024-11-24T06:42:09.677+0000] {processor.py:161} INFO - Started process (PID=8624) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:42:09.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:42:09.680+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:42:09.680+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:42:09.684+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:42:09.683+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:42:09.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:42:09.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:42:39.984+0000] {processor.py:161} INFO - Started process (PID=8635) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:42:39.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:42:39.987+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:42:39.986+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:42:39.991+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:42:39.990+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:42:39.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:42:40.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:43:10.278+0000] {processor.py:161} INFO - Started process (PID=8646) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:43:10.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:43:10.281+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:43:10.281+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:43:10.285+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:43:10.284+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:43:10.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:43:10.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.028 seconds
[2024-11-24T06:43:40.576+0000] {processor.py:161} INFO - Started process (PID=8657) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:43:40.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:43:40.579+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:43:40.579+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:43:40.583+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:43:40.582+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:43:40.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:43:40.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:44:10.886+0000] {processor.py:161} INFO - Started process (PID=8668) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:44:10.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:44:10.889+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:44:10.888+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:44:10.893+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:44:10.892+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:44:10.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:44:10.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.029 seconds
[2024-11-24T06:44:41.211+0000] {processor.py:161} INFO - Started process (PID=8679) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:44:41.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:44:41.214+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:44:41.213+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:44:41.219+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:44:41.218+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:44:41.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:44:41.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.027 seconds
[2024-11-24T06:45:11.499+0000] {processor.py:161} INFO - Started process (PID=8690) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:45:11.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:45:11.502+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:45:11.502+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:45:11.507+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:45:11.505+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:45:11.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:45:11.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.023 seconds
[2024-11-24T06:45:41.791+0000] {processor.py:161} INFO - Started process (PID=8701) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:45:41.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:45:41.794+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:45:41.793+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:45:41.797+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:45:41.796+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:45:41.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:45:41.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.026 seconds
[2024-11-24T06:46:12.066+0000] {processor.py:161} INFO - Started process (PID=8712) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:46:12.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:46:12.069+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:46:12.068+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:46:12.073+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:46:12.071+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:46:12.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:46:12.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.029 seconds
[2024-11-24T06:46:42.366+0000] {processor.py:161} INFO - Started process (PID=8723) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:46:42.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:46:42.369+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:46:42.368+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:46:42.373+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:46:42.371+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:46:42.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:46:42.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.029 seconds
[2024-11-24T06:47:12.656+0000] {processor.py:161} INFO - Started process (PID=8734) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:47:12.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:47:12.659+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:47:12.659+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:47:12.663+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:47:12.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:47:12.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:47:12.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.029 seconds
[2024-11-24T06:47:42.949+0000] {processor.py:161} INFO - Started process (PID=8745) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:47:42.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:47:42.952+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:47:42.952+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:47:42.956+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:47:42.955+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:47:42.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:47:42.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.029 seconds
[2024-11-24T06:48:13.220+0000] {processor.py:161} INFO - Started process (PID=8756) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:48:13.221+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:48:13.223+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:48:13.222+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:48:13.227+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:48:13.226+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:48:13.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:48:13.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:48:43.508+0000] {processor.py:161} INFO - Started process (PID=8767) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:48:43.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:48:43.510+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:48:43.510+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:48:43.513+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:48:43.512+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:48:43.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:48:43.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.019 seconds
[2024-11-24T06:49:13.858+0000] {processor.py:161} INFO - Started process (PID=8778) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:49:13.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:49:13.861+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:49:13.861+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:49:13.866+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:49:13.864+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:49:13.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:49:13.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:49:44.256+0000] {processor.py:161} INFO - Started process (PID=8789) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:49:44.257+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:49:44.259+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:49:44.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:49:44.263+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:49:44.262+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:49:44.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:49:44.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:50:14.597+0000] {processor.py:161} INFO - Started process (PID=8800) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:50:14.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:50:14.600+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:50:14.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:50:14.604+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:50:14.603+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:50:14.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:50:14.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:50:44.954+0000] {processor.py:161} INFO - Started process (PID=8811) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:50:44.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:50:44.957+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:50:44.957+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:50:44.961+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:50:44.960+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:50:44.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:50:44.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:51:15.342+0000] {processor.py:161} INFO - Started process (PID=8822) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:51:15.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:51:15.345+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:51:15.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:51:15.349+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:51:15.348+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:51:15.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:51:15.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:51:45.731+0000] {processor.py:161} INFO - Started process (PID=8833) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:51:45.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:51:45.736+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:51:45.735+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:51:45.741+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:51:45.739+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:51:45.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:51:45.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.034 seconds
[2024-11-24T06:52:16.048+0000] {processor.py:161} INFO - Started process (PID=8844) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:52:16.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:52:16.051+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:52:16.050+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:52:16.055+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:52:16.054+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:52:16.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:52:16.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:52:46.378+0000] {processor.py:161} INFO - Started process (PID=8855) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:52:46.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:52:46.381+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:52:46.381+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:52:46.384+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:52:46.383+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:52:46.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:52:46.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.027 seconds
[2024-11-24T06:53:16.695+0000] {processor.py:161} INFO - Started process (PID=8866) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:53:16.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:53:16.699+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:53:16.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:53:16.703+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:53:16.702+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:53:16.703+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:53:16.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:53:47.076+0000] {processor.py:161} INFO - Started process (PID=8877) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:53:47.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:53:47.079+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:53:47.079+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:53:47.084+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:53:47.082+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:53:47.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:53:47.101+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:54:17.439+0000] {processor.py:161} INFO - Started process (PID=8888) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:54:17.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:54:17.442+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:54:17.441+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:54:17.446+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:54:17.445+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:54:17.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:54:17.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:54:47.822+0000] {processor.py:161} INFO - Started process (PID=8899) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:54:47.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:54:47.825+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:54:47.825+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:54:47.829+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:54:47.828+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:54:47.829+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:54:47.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.029 seconds
[2024-11-24T06:55:18.163+0000] {processor.py:161} INFO - Started process (PID=8910) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:55:18.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:55:18.166+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:55:18.165+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:55:18.170+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:55:18.169+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:55:18.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:55:18.186+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.030 seconds
[2024-11-24T06:55:48.496+0000] {processor.py:161} INFO - Started process (PID=8920) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:55:48.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:55:48.498+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:55:48.498+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:55:48.502+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:55:48.501+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:55:48.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:55:48.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.028 seconds
[2024-11-24T06:56:18.824+0000] {processor.py:161} INFO - Started process (PID=8931) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:56:18.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:56:18.827+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:56:18.827+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:56:18.831+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:56:18.830+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:56:18.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:56:18.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.031 seconds
[2024-11-24T06:56:49.110+0000] {processor.py:161} INFO - Started process (PID=8942) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:56:49.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:56:49.112+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:56:49.112+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:56:49.115+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:56:49.114+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:56:49.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:56:49.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.019 seconds
[2024-11-24T06:57:19.360+0000] {processor.py:161} INFO - Started process (PID=8953) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:57:19.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:57:19.364+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:57:19.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:57:19.370+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:57:19.368+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:57:19.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:57:19.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.047 seconds
[2024-11-24T06:57:49.624+0000] {processor.py:161} INFO - Started process (PID=8965) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:57:49.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:57:49.630+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:57:49.630+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:57:49.637+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:57:49.635+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:57:49.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:57:49.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.038 seconds
[2024-11-24T06:58:25.893+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:58:25.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:58:25.899+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:58:25.898+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:58:25.904+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:58:25.903+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:58:25.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:58:25.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.027 seconds
[2024-11-24T06:58:56.185+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:58:56.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:58:56.189+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:58:56.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:58:56.194+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:58:56.193+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:58:56.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:58:56.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.036 seconds
[2024-11-24T06:59:26.451+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:59:26.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:59:26.454+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:59:26.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:59:26.458+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:59:26.457+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:59:26.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:59:26.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.028 seconds
[2024-11-24T06:59:56.766+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:59:56.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T06:59:56.769+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:59:56.769+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:59:56.774+0000] {logging_mixin.py:188} INFO - [2024-11-24T06:59:56.773+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T06:59:56.774+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T06:59:56.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.034 seconds
[2024-11-24T07:00:27.034+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:00:27.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:00:27.037+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:00:27.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:00:27.041+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:00:27.040+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ETL_proj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_proj.py", line 10, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-11-24T07:00:27.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:00:27.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_proj.py took 0.033 seconds
[2024-11-24T07:00:45.231+0000] {processor.py:161} INFO - Started process (PID=267) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:00:45.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:00:45.235+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:00:45.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:00:46.182+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202001-citibike-tripdata.csv
[2024-11-24T07:00:46.887+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202002-citibike-tripdata.csv
[2024-11-24T07:00:47.538+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202003-citibike-tripdata.csv
[2024-11-24T07:00:48.123+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202004-citibike-tripdata.csv
[2024-11-24T07:00:48.823+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202005-citibike-tripdata.csv
[2024-11-24T07:00:49.630+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202006-citibike-tripdata.csv
[2024-11-24T07:00:50.454+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202007-citibike-tripdata.csv
[2024-11-24T07:00:51.279+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202008-citibike-tripdata.csv
[2024-11-24T07:00:52.123+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202009-citibike-tripdata.csv
[2024-11-24T07:00:52.812+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202010-citibike-tripdata.csv
[2024-11-24T07:00:53.480+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202011-citibike-tripdata.csv
[2024-11-24T07:00:54.052+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202012-citibike-tripdata.csv
[2024-11-24T07:00:54.619+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202101-citibike-tripdata.csv
[2024-11-24T07:00:55.126+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202102-citibike-tripdata.csv
[2024-11-24T07:00:55.799+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202103-citibike-tripdata.csv
[2024-11-24T07:00:56.489+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202104-citibike-tripdata.csv
[2024-11-24T07:00:57.318+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202105-citibike-tripdata.csv
[2024-11-24T07:00:58.266+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202106-citibike-tripdata.csv
[2024-11-24T07:00:59.327+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202107-citibike-tripdata.csv
[2024-11-24T07:01:00.406+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202108-citibike-tripdata.csv
[2024-11-24T07:01:01.611+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202109-citibike-tripdata.csv
[2024-11-24T07:01:02.702+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202110-citibike-tripdata.csv
[2024-11-24T07:01:03.699+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202111-citibike-tripdata.csv
[2024-11-24T07:01:04.617+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202112-citibike-tripdata.csv
[2024-11-24T07:01:05.331+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202201-citibike-tripdata.csv
[2024-11-24T07:01:06.148+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202202-citibike-tripdata.csv
[2024-11-24T07:01:07.089+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202203-citibike-tripdata.csv
[2024-11-24T07:01:08.016+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202204-citibike-tripdata.csv
[2024-11-24T07:01:09.030+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202205-citibike-tripdata.csv
[2024-11-24T07:01:10.083+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202206-citibike-tripdata.csv
[2024-11-24T07:01:11.223+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202207-citbike-tripdata.csv
[2024-11-24T07:01:15.242+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:01:15.240+0000] {timeout.py:68} ERROR - Process timed out, PID: 267
[2024-11-24T07:03:25.594+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:03:25.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:03:25.597+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:03:25.596+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:03:26.411+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202001-citibike-tripdata.csv
[2024-11-24T07:03:27.088+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202002-citibike-tripdata.csv
[2024-11-24T07:03:27.783+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202003-citibike-tripdata.csv
[2024-11-24T07:03:28.379+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202004-citibike-tripdata.csv
[2024-11-24T07:03:29.094+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202005-citibike-tripdata.csv
[2024-11-24T07:03:29.853+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202006-citibike-tripdata.csv
[2024-11-24T07:03:30.617+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202007-citibike-tripdata.csv
[2024-11-24T07:03:31.407+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202008-citibike-tripdata.csv
[2024-11-24T07:03:32.290+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202009-citibike-tripdata.csv
[2024-11-24T07:03:32.959+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202010-citibike-tripdata.csv
[2024-11-24T07:03:33.574+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202011-citibike-tripdata.csv
[2024-11-24T07:03:34.113+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202012-citibike-tripdata.csv
[2024-11-24T07:03:34.675+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202101-citibike-tripdata.csv
[2024-11-24T07:03:35.154+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202102-citibike-tripdata.csv
[2024-11-24T07:03:35.841+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202103-citibike-tripdata.csv
[2024-11-24T07:03:36.517+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202104-citibike-tripdata.csv
[2024-11-24T07:03:37.312+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202105-citibike-tripdata.csv
[2024-11-24T07:03:38.306+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202106-citibike-tripdata.csv
[2024-11-24T07:03:39.397+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202107-citibike-tripdata.csv
[2024-11-24T07:03:40.470+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202108-citibike-tripdata.csv
[2024-11-24T07:03:41.646+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202109-citibike-tripdata.csv
[2024-11-24T07:03:42.984+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202110-citibike-tripdata.csv
[2024-11-24T07:03:43.960+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202111-citibike-tripdata.csv
[2024-11-24T07:03:44.793+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202112-citibike-tripdata.csv
[2024-11-24T07:03:45.550+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202201-citibike-tripdata.csv
[2024-11-24T07:03:46.287+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202202-citibike-tripdata.csv
[2024-11-24T07:03:47.150+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202203-citibike-tripdata.csv
[2024-11-24T07:03:48.149+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202204-citibike-tripdata.csv
[2024-11-24T07:03:49.231+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202205-citibike-tripdata.csv
[2024-11-24T07:03:50.379+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202206-citibike-tripdata.csv
[2024-11-24T07:03:51.577+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202207-citbike-tripdata.csv
[2024-11-24T07:03:52.932+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202208-citibike-tripdata.csv
[2024-11-24T07:03:54.081+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202209-citibike-tripdata.csv
[2024-11-24T07:03:55.244+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202210-citibike-tripdata.csv
[2024-11-24T07:03:55.601+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:03:55.601+0000] {timeout.py:68} ERROR - Process timed out, PID: 306
[2024-11-24T07:04:26.067+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:04:26.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:04:26.069+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:04:26.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:04:26.907+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202001-citibike-tripdata.csv
[2024-11-24T07:04:27.605+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202002-citibike-tripdata.csv
[2024-11-24T07:04:28.277+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202003-citibike-tripdata.csv
[2024-11-24T07:04:28.831+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202004-citibike-tripdata.csv
[2024-11-24T07:04:29.510+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202005-citibike-tripdata.csv
[2024-11-24T07:04:30.253+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202006-citibike-tripdata.csv
[2024-11-24T07:04:31.023+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202007-citibike-tripdata.csv
[2024-11-24T07:04:31.813+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202008-citibike-tripdata.csv
[2024-11-24T07:04:32.603+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202009-citibike-tripdata.csv
[2024-11-24T07:04:35.155+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202010-citibike-tripdata.csv
[2024-11-24T07:04:35.766+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202011-citibike-tripdata.csv
[2024-11-24T07:04:36.276+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202012-citibike-tripdata.csv
[2024-11-24T07:04:36.794+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202101-citibike-tripdata.csv
[2024-11-24T07:04:37.221+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202102-citibike-tripdata.csv
[2024-11-24T07:04:37.809+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202103-citibike-tripdata.csv
[2024-11-24T07:04:38.445+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202104-citibike-tripdata.csv
[2024-11-24T07:04:39.202+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202105-citibike-tripdata.csv
[2024-11-24T07:04:40.140+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202106-citibike-tripdata.csv
[2024-11-24T07:04:41.089+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202107-citibike-tripdata.csv
[2024-11-24T07:04:42.114+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202108-citibike-tripdata.csv
[2024-11-24T07:04:43.068+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202109-citibike-tripdata.csv
[2024-11-24T07:04:44.033+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202110-citibike-tripdata.csv
[2024-11-24T07:04:44.854+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202111-citibike-tripdata.csv
[2024-11-24T07:04:45.633+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202112-citibike-tripdata.csv
[2024-11-24T07:04:46.346+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202201-citibike-tripdata.csv
[2024-11-24T07:04:47.087+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202202-citibike-tripdata.csv
[2024-11-24T07:04:47.927+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202203-citibike-tripdata.csv
[2024-11-24T07:04:48.824+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202204-citibike-tripdata.csv
[2024-11-24T07:04:49.833+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202205-citibike-tripdata.csv
[2024-11-24T07:04:50.864+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202206-citibike-tripdata.csv
[2024-11-24T07:04:51.989+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202207-citbike-tripdata.csv
[2024-11-24T07:04:53.046+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202208-citibike-tripdata.csv
[2024-11-24T07:04:54.096+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202209-citibike-tripdata.csv
[2024-11-24T07:04:55.087+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202210-citibike-tripdata.csv
[2024-11-24T07:04:56.030+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202211-citibike-tripdata.csv
[2024-11-24T07:04:56.074+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:04:56.073+0000] {timeout.py:68} ERROR - Process timed out, PID: 328
[2024-11-24T07:30:18.685+0000] {processor.py:161} INFO - Started process (PID=768) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:30:18.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:30:18.689+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:30:18.689+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:30:19.503+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202001-citibike-tripdata.csv
[2024-11-24T07:30:20.185+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202002-citibike-tripdata.csv
[2024-11-24T07:30:21.919+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202003-citibike-tripdata.csv
[2024-11-24T07:30:22.940+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202004-citibike-tripdata.csv
[2024-11-24T07:30:23.555+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202005-citibike-tripdata.csv
[2024-11-24T07:30:24.332+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202006-citibike-tripdata.csv
[2024-11-24T07:30:27.358+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202007-citibike-tripdata.csv
[2024-11-24T07:30:28.132+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202008-citibike-tripdata.csv
[2024-11-24T07:30:28.930+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202009-citibike-tripdata.csv
[2024-11-24T07:30:29.566+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202010-citibike-tripdata.csv
[2024-11-24T07:30:30.261+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202011-citibike-tripdata.csv
[2024-11-24T07:30:30.809+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202012-citibike-tripdata.csv
[2024-11-24T07:30:31.340+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202101-citibike-tripdata.csv
[2024-11-24T07:30:31.770+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202102-citibike-tripdata.csv
[2024-11-24T07:30:32.369+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202103-citibike-tripdata.csv
[2024-11-24T07:30:33.011+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202104-citibike-tripdata.csv
[2024-11-24T07:30:33.784+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202105-citibike-tripdata.csv
[2024-11-24T07:30:34.667+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202106-citibike-tripdata.csv
[2024-11-24T07:30:35.647+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202107-citibike-tripdata.csv
[2024-11-24T07:30:36.653+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202108-citibike-tripdata.csv
[2024-11-24T07:30:37.783+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202109-citibike-tripdata.csv
[2024-11-24T07:30:38.751+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202110-citibike-tripdata.csv
[2024-11-24T07:30:39.555+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202111-citibike-tripdata.csv
[2024-11-24T07:30:40.406+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202112-citibike-tripdata.csv
[2024-11-24T07:30:41.107+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202201-citibike-tripdata.csv
[2024-11-24T07:30:41.867+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202202-citibike-tripdata.csv
[2024-11-24T07:30:42.792+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202203-citibike-tripdata.csv
[2024-11-24T07:30:43.763+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202204-citibike-tripdata.csv
[2024-11-24T07:30:44.809+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202205-citibike-tripdata.csv
[2024-11-24T07:30:46.015+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202206-citibike-tripdata.csv
[2024-11-24T07:30:47.226+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202207-citbike-tripdata.csv
[2024-11-24T07:30:48.278+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202208-citibike-tripdata.csv
[2024-11-24T07:30:48.695+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:30:48.694+0000] {timeout.py:68} ERROR - Process timed out, PID: 768
[2024-11-24T07:31:19.106+0000] {processor.py:161} INFO - Started process (PID=806) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:31:19.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:31:19.109+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:31:19.109+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:31:19.888+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202001-citibike-tripdata.csv
[2024-11-24T07:31:20.561+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202002-citibike-tripdata.csv
[2024-11-24T07:31:21.246+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202003-citibike-tripdata.csv
[2024-11-24T07:31:21.814+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202004-citibike-tripdata.csv
[2024-11-24T07:31:22.470+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202005-citibike-tripdata.csv
[2024-11-24T07:31:23.214+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202006-citibike-tripdata.csv
[2024-11-24T07:31:23.975+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202007-citibike-tripdata.csv
[2024-11-24T07:31:24.721+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202008-citibike-tripdata.csv
[2024-11-24T07:31:25.508+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202009-citibike-tripdata.csv
[2024-11-24T07:31:26.156+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202010-citibike-tripdata.csv
[2024-11-24T07:31:26.801+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202011-citibike-tripdata.csv
[2024-11-24T07:31:27.349+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202012-citibike-tripdata.csv
[2024-11-24T07:31:27.897+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202101-citibike-tripdata.csv
[2024-11-24T07:31:28.375+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202102-citibike-tripdata.csv
[2024-11-24T07:31:28.991+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202103-citibike-tripdata.csv
[2024-11-24T07:31:29.628+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202104-citibike-tripdata.csv
[2024-11-24T07:31:30.355+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202105-citibike-tripdata.csv
[2024-11-24T07:31:31.252+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202106-citibike-tripdata.csv
[2024-11-24T07:31:32.228+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202107-citibike-tripdata.csv
[2024-11-24T07:31:33.232+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202108-citibike-tripdata.csv
[2024-11-24T07:31:34.215+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202109-citibike-tripdata.csv
[2024-11-24T07:31:35.273+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202110-citibike-tripdata.csv
[2024-11-24T07:31:36.162+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202111-citibike-tripdata.csv
[2024-11-24T07:31:36.985+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202112-citibike-tripdata.csv
[2024-11-24T07:31:37.656+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202201-citibike-tripdata.csv
[2024-11-24T07:31:38.400+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202202-citibike-tripdata.csv
[2024-11-24T07:31:41.959+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202203-citibike-tripdata.csv
[2024-11-24T07:31:42.875+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202204-citibike-tripdata.csv
[2024-11-24T07:31:43.852+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202205-citibike-tripdata.csv
[2024-11-24T07:31:44.859+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202206-citibike-tripdata.csv
[2024-11-24T07:31:45.932+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202207-citbike-tripdata.csv
[2024-11-24T07:31:46.926+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202208-citibike-tripdata.csv
[2024-11-24T07:31:47.998+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202209-citibike-tripdata.csv
[2024-11-24T07:31:49.116+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:31:49.115+0000] {timeout.py:68} ERROR - Process timed out, PID: 806
[2024-11-24T07:32:19.530+0000] {processor.py:161} INFO - Started process (PID=828) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:32:19.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:32:19.535+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:32:19.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:32:20.375+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202001-citibike-tripdata.csv
[2024-11-24T07:32:20.998+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202002-citibike-tripdata.csv
[2024-11-24T07:32:21.622+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202003-citibike-tripdata.csv
[2024-11-24T07:32:22.156+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202004-citibike-tripdata.csv
[2024-11-24T07:32:22.825+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202005-citibike-tripdata.csv
[2024-11-24T07:32:23.572+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202006-citibike-tripdata.csv
[2024-11-24T07:32:24.321+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202007-citibike-tripdata.csv
[2024-11-24T07:32:25.060+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202008-citibike-tripdata.csv
[2024-11-24T07:32:25.856+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202009-citibike-tripdata.csv
[2024-11-24T07:32:26.531+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202010-citibike-tripdata.csv
[2024-11-24T07:32:27.194+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202011-citibike-tripdata.csv
[2024-11-24T07:32:27.737+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202012-citibike-tripdata.csv
[2024-11-24T07:32:28.261+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202101-citibike-tripdata.csv
[2024-11-24T07:32:28.740+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202102-citibike-tripdata.csv
[2024-11-24T07:32:29.391+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202103-citibike-tripdata.csv
[2024-11-24T07:32:30.042+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202104-citibike-tripdata.csv
[2024-11-24T07:32:30.819+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202105-citibike-tripdata.csv
[2024-11-24T07:32:31.895+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202106-citibike-tripdata.csv
[2024-11-24T07:32:32.843+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202107-citibike-tripdata.csv
[2024-11-24T07:32:34.043+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202108-citibike-tripdata.csv
[2024-11-24T07:32:35.393+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202109-citibike-tripdata.csv
[2024-11-24T07:32:36.468+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202110-citibike-tripdata.csv
[2024-11-24T07:32:37.332+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202111-citibike-tripdata.csv
[2024-11-24T07:32:38.153+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202112-citibike-tripdata.csv
[2024-11-24T07:32:38.827+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202201-citibike-tripdata.csv
[2024-11-24T07:32:39.583+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202202-citibike-tripdata.csv
[2024-11-24T07:32:40.372+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202203-citibike-tripdata.csv
[2024-11-24T07:32:41.254+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202204-citibike-tripdata.csv
[2024-11-24T07:32:42.326+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202205-citibike-tripdata.csv
[2024-11-24T07:32:43.561+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202206-citibike-tripdata.csv
[2024-11-24T07:32:44.756+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202207-citbike-tripdata.csv
[2024-11-24T07:32:45.881+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202208-citibike-tripdata.csv
[2024-11-24T07:32:49.536+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:32:49.536+0000] {timeout.py:68} ERROR - Process timed out, PID: 828
[2024-11-24T07:33:19.926+0000] {processor.py:161} INFO - Started process (PID=850) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:33:19.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:33:19.934+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:33:19.934+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:33:20.689+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202001-citibike-tripdata.csv
[2024-11-24T07:33:21.340+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202002-citibike-tripdata.csv
[2024-11-24T07:33:21.997+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202003-citibike-tripdata.csv
[2024-11-24T07:33:22.548+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202004-citibike-tripdata.csv
[2024-11-24T07:33:23.318+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202005-citibike-tripdata.csv
[2024-11-24T07:33:24.024+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202006-citibike-tripdata.csv
[2024-11-24T07:33:24.780+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202007-citibike-tripdata.csv
[2024-11-24T07:33:25.511+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202008-citibike-tripdata.csv
[2024-11-24T07:33:26.333+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202009-citibike-tripdata.csv
[2024-11-24T07:33:27.017+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202010-citibike-tripdata.csv
[2024-11-24T07:33:27.635+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202011-citibike-tripdata.csv
[2024-11-24T07:33:28.155+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202012-citibike-tripdata.csv
[2024-11-24T07:33:28.672+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202101-citibike-tripdata.csv
[2024-11-24T07:33:29.132+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202102-citibike-tripdata.csv
[2024-11-24T07:33:29.788+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202103-citibike-tripdata.csv
[2024-11-24T07:33:30.448+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202104-citibike-tripdata.csv
[2024-11-24T07:33:31.294+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202105-citibike-tripdata.csv
[2024-11-24T07:33:32.264+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202106-citibike-tripdata.csv
[2024-11-24T07:33:33.239+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202107-citibike-tripdata.csv
[2024-11-24T07:33:34.261+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202108-citibike-tripdata.csv
[2024-11-24T07:33:35.314+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202109-citibike-tripdata.csv
[2024-11-24T07:33:36.216+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202110-citibike-tripdata.csv
[2024-11-24T07:33:37.003+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202111-citibike-tripdata.csv
[2024-11-24T07:33:37.761+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202112-citibike-tripdata.csv
[2024-11-24T07:33:38.492+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202201-citibike-tripdata.csv
[2024-11-24T07:33:39.289+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202202-citibike-tripdata.csv
[2024-11-24T07:33:40.080+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202203-citibike-tripdata.csv
[2024-11-24T07:33:40.966+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202204-citibike-tripdata.csv
[2024-11-24T07:33:41.895+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202205-citibike-tripdata.csv
[2024-11-24T07:33:42.866+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202206-citibike-tripdata.csv
[2024-11-24T07:33:43.878+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202207-citbike-tripdata.csv
[2024-11-24T07:33:44.948+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202208-citibike-tripdata.csv
[2024-11-24T07:33:45.996+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202209-citibike-tripdata.csv
[2024-11-24T07:33:47.078+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202210-citibike-tripdata.csv
[2024-11-24T07:33:48.115+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202211-citibike-tripdata.csv
[2024-11-24T07:33:49.937+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:33:49.936+0000] {timeout.py:68} ERROR - Process timed out, PID: 850
[2024-11-24T07:34:20.422+0000] {processor.py:161} INFO - Started process (PID=872) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:34:20.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:34:20.427+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:34:20.426+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:34:21.266+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202001-citibike-tripdata.csv
[2024-11-24T07:34:21.919+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202002-citibike-tripdata.csv
[2024-11-24T07:34:22.578+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202003-citibike-tripdata.csv
[2024-11-24T07:34:23.117+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202004-citibike-tripdata.csv
[2024-11-24T07:34:23.760+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202005-citibike-tripdata.csv
[2024-11-24T07:34:24.503+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202006-citibike-tripdata.csv
[2024-11-24T07:34:25.241+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202007-citibike-tripdata.csv
[2024-11-24T07:34:25.969+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202008-citibike-tripdata.csv
[2024-11-24T07:34:26.747+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202009-citibike-tripdata.csv
[2024-11-24T07:34:27.397+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202010-citibike-tripdata.csv
[2024-11-24T07:34:28.029+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202011-citibike-tripdata.csv
[2024-11-24T07:34:28.569+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202012-citibike-tripdata.csv
[2024-11-24T07:34:29.105+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202101-citibike-tripdata.csv
[2024-11-24T07:34:29.548+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202102-citibike-tripdata.csv
[2024-11-24T07:34:30.182+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202103-citibike-tripdata.csv
[2024-11-24T07:34:32.322+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202104-citibike-tripdata.csv
[2024-11-24T07:34:33.087+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202105-citibike-tripdata.csv
[2024-11-24T07:34:37.609+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202106-citibike-tripdata.csv
[2024-11-24T07:34:38.554+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202107-citibike-tripdata.csv
[2024-11-24T07:34:39.489+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202108-citibike-tripdata.csv
[2024-11-24T07:34:44.977+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202109-citibike-tripdata.csv
[2024-11-24T07:34:45.893+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202110-citibike-tripdata.csv
[2024-11-24T07:34:46.708+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202111-citibike-tripdata.csv
[2024-11-24T07:34:47.483+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202112-citibike-tripdata.csv
[2024-11-24T07:34:48.099+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202201-citibike-tripdata.csv
[2024-11-24T07:34:48.827+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202202-citibike-tripdata.csv
[2024-11-24T07:34:49.618+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202203-citibike-tripdata.csv
[2024-11-24T07:34:50.434+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:34:50.434+0000] {timeout.py:68} ERROR - Process timed out, PID: 872
[2024-11-24T07:35:20.865+0000] {processor.py:161} INFO - Started process (PID=894) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:35:20.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:35:20.870+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:35:20.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:35:21.746+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202001-citibike-tripdata.csv
[2024-11-24T07:35:22.432+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202002-citibike-tripdata.csv
[2024-11-24T07:35:23.107+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202003-citibike-tripdata.csv
[2024-11-24T07:35:23.800+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202004-citibike-tripdata.csv
[2024-11-24T07:35:24.425+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202005-citibike-tripdata.csv
[2024-11-24T07:35:25.144+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202006-citibike-tripdata.csv
[2024-11-24T07:35:25.947+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202007-citibike-tripdata.csv
[2024-11-24T07:35:28.983+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202008-citibike-tripdata.csv
[2024-11-24T07:35:29.796+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202009-citibike-tripdata.csv
[2024-11-24T07:35:30.430+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202010-citibike-tripdata.csv
[2024-11-24T07:35:31.071+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202011-citibike-tripdata.csv
[2024-11-24T07:35:31.602+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202012-citibike-tripdata.csv
[2024-11-24T07:35:32.911+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202101-citibike-tripdata.csv
[2024-11-24T07:35:33.364+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202102-citibike-tripdata.csv
[2024-11-24T07:35:34.064+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202103-citibike-tripdata.csv
[2024-11-24T07:35:34.697+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202104-citibike-tripdata.csv
[2024-11-24T07:35:35.467+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202105-citibike-tripdata.csv
[2024-11-24T07:35:36.415+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202106-citibike-tripdata.csv
[2024-11-24T07:35:37.403+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202107-citibike-tripdata.csv
[2024-11-24T07:35:38.404+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202108-citibike-tripdata.csv
[2024-11-24T07:35:39.458+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202109-citibike-tripdata.csv
[2024-11-24T07:35:40.465+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202110-citibike-tripdata.csv
[2024-11-24T07:35:41.377+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202111-citibike-tripdata.csv
[2024-11-24T07:35:42.223+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202112-citibike-tripdata.csv
[2024-11-24T07:35:42.962+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202201-citibike-tripdata.csv
[2024-11-24T07:35:43.731+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202202-citibike-tripdata.csv
[2024-11-24T07:35:44.566+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202203-citibike-tripdata.csv
[2024-11-24T07:35:48.640+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202204-citibike-tripdata.csv
[2024-11-24T07:35:49.637+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202205-citibike-tripdata.csv
[2024-11-24T07:35:50.643+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202206-citibike-tripdata.csv
[2024-11-24T07:35:50.875+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:35:50.875+0000] {timeout.py:68} ERROR - Process timed out, PID: 894
[2024-11-24T07:36:21.394+0000] {processor.py:161} INFO - Started process (PID=917) to work on /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:36:21.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_proj.py for tasks to queue
[2024-11-24T07:36:21.398+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:36:21.397+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_proj.py
[2024-11-24T07:36:24.009+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202001-citibike-tripdata.csv
[2024-11-24T07:36:24.650+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202002-citibike-tripdata.csv
[2024-11-24T07:36:25.260+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202003-citibike-tripdata.csv
[2024-11-24T07:36:25.785+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202004-citibike-tripdata.csv
[2024-11-24T07:36:26.410+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202005-citibike-tripdata.csv
[2024-11-24T07:36:27.103+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202006-citibike-tripdata.csv
[2024-11-24T07:36:29.875+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202007-citibike-tripdata.csv
[2024-11-24T07:36:30.608+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202008-citibike-tripdata.csv
[2024-11-24T07:36:31.372+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202009-citibike-tripdata.csv
[2024-11-24T07:36:32.074+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202010-citibike-tripdata.csv
[2024-11-24T07:36:32.687+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202011-citibike-tripdata.csv
[2024-11-24T07:36:33.211+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202012-citibike-tripdata.csv
[2024-11-24T07:36:34.461+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202101-citibike-tripdata.csv
[2024-11-24T07:36:34.921+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202102-citibike-tripdata.csv
[2024-11-24T07:36:35.563+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202103-citibike-tripdata.csv
[2024-11-24T07:36:36.217+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202104-citibike-tripdata.csv
[2024-11-24T07:36:37.028+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202105-citibike-tripdata.csv
[2024-11-24T07:36:37.935+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202106-citibike-tripdata.csv
[2024-11-24T07:36:38.923+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202107-citibike-tripdata.csv
[2024-11-24T07:36:39.949+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202108-citibike-tripdata.csv
[2024-11-24T07:36:40.971+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202109-citibike-tripdata.csv
[2024-11-24T07:36:41.947+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202110-citibike-tripdata.csv
[2024-11-24T07:36:42.831+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202111-citibike-tripdata.csv
[2024-11-24T07:36:43.710+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202112-citibike-tripdata.csv
[2024-11-24T07:36:44.366+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202201-citibike-tripdata.csv
[2024-11-24T07:36:45.170+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202202-citibike-tripdata.csv
[2024-11-24T07:36:46.011+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202203-citibike-tripdata.csv
[2024-11-24T07:36:46.916+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202204-citibike-tripdata.csv
[2024-11-24T07:36:47.866+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202205-citibike-tripdata.csv
[2024-11-24T07:36:48.983+0000] {logging_mixin.py:188} INFO - Successfully processed: JC-202206-citibike-tripdata.csv
[2024-11-24T07:36:51.411+0000] {logging_mixin.py:188} INFO - [2024-11-24T07:36:51.410+0000] {timeout.py:68} ERROR - Process timed out, PID: 917
